from __future__ import annotations

import sys
import unittest
from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PACKAGE_DIR.parent))

from comfyui_anime_character_selector import NODE_CLASS_MAPPINGS  # noqa: E402
from comfyui_anime_character_selector import anime_character_selector as selector  # noqa: E402


class AnimeCharacterSelectorTests(unittest.TestCase):
    def setUp(self) -> None:
        self.node = NODE_CLASS_MAPPINGS["AnimeCharacterSelectorCN"]()

    def test_bundles_revised_wai_v123_list(self) -> None:
        self.assertEqual(5680, len(selector._CHARACTER_MAP))
        self.assertEqual(5681, len(selector._CHINESE_OPTIONS))
        self.assertEqual(5681, len(selector._ENGLISH_OPTIONS))

    def test_representative_revised_game_mappings(self) -> None:
        expected = {
            "安朵丝（少女前线2：追放）": "andoris (girls' frontline 2)",
            "绯（少女前线2：追放）": "centaureissi (girls' frontline 2)",
            "奇塔（少女前线2：追放）": "cheeta (girls' frontline 2)",
            "寇尔芙（少女前线2：追放）": "colphne (girls' frontline 2)",
            "黛烟（少女前线2：追放）": "daiyan (girls' frontline 2)",
            "杜莎妮（少女前线2：追放）": "dushevnaya (girls' frontline 2)",
            "芙洛伦（少女前线2：追放）": "florence (girls' frontline 2)",
            "闪电（少女前线2：追放）": "groza (girls' frontline 2)",
            "海伦（少女前线2：追放）": "helen (girls' frontline 2)",
            "绛雨（少女前线2：追放）": "jiangyu (girls' frontline 2)",
            "可露凯（少女前线2：追放）": "klukai (girls' frontline 2)",
            "克罗丽科（少女前线2：追放）": "krolik (girls' frontline 2)",
            "科谢尼娅（少女前线2：追放）": "ksenia (girls' frontline 2)",
            "莱娅（少女前线2：追放）": "leva (girls' frontline 2)",
            "刘易斯（少女前线2：追放）": "lewis (girls' frontline 2)",
            "莉塔拉（少女前线2：追放）": "littara (girls' frontline 2)",
            "洛塔（少女前线2：追放）": "lotta (girls' frontline 2)",
            "玛绮朵（少女前线2：追放）": "makiatto (girls' frontline 2)",
            "米什提（少女前线2：追放）": "mechty (girls' frontline 2)",
            "莫辛纳甘（少女前线2：追放）": "mosin-nagant (girls' frontline 2)",
            "纳甘（少女前线2：追放）": "nagant (girls' frontline 2)",
            "纳美西丝（少女前线2：追放）": "nemesis (girls' frontline 2)",
            "妮基塔（少女前线2：追放）": "nikketa (girls' frontline 2)",
            "佩里缇亚（少女前线2：追放）": "peritya (girls' frontline 2)",
            "琼玖（少女前线2：追放）": "qiongjiu (girls' frontline 2)",
            "塞布丽娜（少女前线2：追放）": "sabrina (girls' frontline 2)",
            "夏克里（少女前线2：追放）": "sharkry (girls' frontline 2)",
            "春田（少女前线2：追放）": "springfield (girls' frontline 2)",
            "索米（少女前线2：追放）": "suomi (girls' frontline 2)",
            "托洛洛（少女前线2：追放）": "tololo (girls' frontline 2)",
            "乌尔丽德（少女前线2：追放）": "ullrid (girls' frontline 2)",
            "维克托（少女前线2：追放）": "vector (girls' frontline 2)",
            "维普蕾（少女前线2：追放）": "vepley (girls' frontline 2)",
            "朝晖（少女前线2：追放）": "zhaohui (girls' frontline 2)",
            "塞西尔·柯尔米（反叛的鲁路修）": "cecile croomy",
            "吉诺·温伯格（反叛的鲁路修）": "gino weinberg",
            "春川风希（莉可丽丝）": "harukawa fuki",
            "杰里米亚·哥特瓦尔德（反叛的鲁路修）": "jeremiah gottwald",
            "金格·布拉德雷（钢之炼金术士）": "king bradley",
            "兰芳（钢之炼金术士）": "lan fan",
            "姚麟（钢之炼金术士）": "ling yao",
            "真岛（莉可丽丝）": "majima (lycoris recoil)",
            "张梅（钢之炼金术士）": "may chang",
            "米卡（莉可丽丝）": "mika (lycoris recoil)",
            "中原瑞希（莉可丽丝）": "nakahara mizuki",
            "妮娜·爱因斯坦（反叛的鲁路修）": "nina einstein",
            "罗洛·兰佩洛基（反叛的鲁路修）": "rolo lamperouge",
            "黍（明日方舟）": "shu (arknights)",
            "阿（明日方舟）": "aak (arknights)",
            "堇（蔚蓝档案）": "sumire (blue archive)",
            "长发公主（胜利女神：NIKKE）": "rapunzel (nikke)",
            "诺伊斯（胜利女神：NIKKE）": "noise (nikke)",
            "佩丽卡（明日方舟终末地）": "perlica (arknights endfield)",
            "爱弥斯（鸣潮）": "aemeath (wuthering waves)",
            "达妮娅（鸣潮）": "denia (wuthering waves)",
            "铃（绝区零）": "belle (zenless zone zero)",
            "安克（胜利女神：NIKKE）": "anchor (nikke)",
            "桑多涅（原神）": "sandrone (genshin impact)",
            "茜特菈莉（原神）": "citlali (genshin impact)",
            "梦见月瑞希（原神）": "yumemizuki mizuki",
            "赤木律子（新世纪福音战士）": "akagi ritsuko",
            "菲·瓦伦丁（星际牛仔）": "faye valentine",
            "桥田至（命运石之门）": "hashida itaru",
            "真锅和（轻音少女）": "manabe nodoka",
            "阿格莱雅（崩坏：星穹铁道）": "aglaea (honkai: star rail)",
            "那刻夏（崩坏：星穹铁道）": "anaxa (honkai: star rail)",
            "遐蝶（崩坏：星穹铁道）": "castorice (honkai: star rail)",
            "赛飞儿（崩坏：星穹铁道）": "cipher (honkai: star rail)",
            "昔涟（崩坏：星穹铁道）": "cyrene (honkai: star rail)",
            "长夜月（崩坏：星穹铁道）": "evernight (honkai: star rail)",
            "风堇（崩坏：星穹铁道）": "hyacine (honkai: star rail)",
            "海瑟音（崩坏：星穹铁道）": "hysilens (honkai: star rail)",
            "万敌（崩坏：星穹铁道）": "mydei (honkai: star rail)",
            "火花（崩坏：星穹铁道）": "sparxie (honkai: star rail)",
            "缇宝（崩坏：星穹铁道）": "tribbie (honkai: star rail)",
            "安卡希雅（尘白禁区）": "acacia (snowbreak)",
            "卜卜（尘白禁区）": "bubu (snowbreak)",
            "猫汐尔（尘白禁区）": "mauxir (snowbreak)",
            "晴（尘白禁区）": "naruse haru (snowbreak)",
            "妮塔（尘白禁区）": "nita (snowbreak)",
            "瑟瑞斯（尘白禁区）": "siris (snowbreak)",
            "肴（尘白禁区）": "yao (snowbreak)",
            "琴诺（尘白禁区）": "cherno kegaard",
            "伊切尔（尘白禁区）": "eatchel gustav",
            "芬妮（尘白禁区）": "fenny golden",
            "里芙（尘白禁区）": "lyfe bestla",
            "恩雅（尘白禁区）": "enya murphy",
            "芙提雅（尘白禁区）": "fritia ignis",
            "凯茜娅（尘白禁区）": "katya klein",
            "茉莉安（尘白禁区）": "marian andreotti",
            "苔丝（尘白禁区）": "tess kotkin",
            "薇蒂雅（尘白禁区）": "vidya shannon",
            "贝尼（黑礁）": "benny (black lagoon)",
            "达奇（黑礁）": "dutch (black lagoon)",
            "法比奥拉（黑礁）": "fabiola iglesias",
            "格蕾特尔（黑礁）": "gretel (black lagoon)",
            "汉塞尔（黑礁）": "hansel (black lagoon)",
            "约兰达（黑礁）": "yolanda (black lagoon)",
            "古河秋生（CLANNAD）": "furukawa akio",
            "古河早苗（CLANNAD）": "furukawa sanae",
            "伊吹风子（CLANNAD）": "ibuki fuuko",
            "宫泽有纪宁（CLANNAD）": "miyazawa yukine",
            "冈崎汐（CLANNAD）": "okazaki ushio",
            "相乐美佐枝（CLANNAD）": "sagara misae",
            "春原芽衣（CLANNAD）": "sunohara mei",
            "春原阳平（CLANNAD）": "sunohara youhei",
            "芳野祐介（CLANNAD）": "yoshino yuusuke",
            "木之本藤隆（魔卡少女樱）": "kinomoto fujitaka",
            "木之本桃矢（魔卡少女樱）": "kinomoto touya",
            "月城雪兔（魔卡少女樱）": "tsukishiro yukito",
            "艾德（星际牛仔）": "edward wong hau pepelu tivrusky iv",
            "艾丽卡·欧维罗（星际牛仔）": "electra ovilo",
            "朱莉娅（星际牛仔）": "julia (cowboy bebop)",
            "比夏斯（星际牛仔）": "vicious (cowboy bebop)",
            "文森特·渥拉裘（星际牛仔）": "vincent volaju",
            "高须龙儿（龙与虎）": "takasu ryuuji",
            "高须泰子（龙与虎）": "takasu yasuko",
            "虚妹（凉宫春日的忧郁）": "kyon's sister",
            "三味线（凉宫春日的忧郁）": "shamisen (suzumiya haruhi)",
            "谷口（凉宫春日的忧郁）": "taniguchi (suzumiya haruhi)",
            "国木田（凉宫春日的忧郁）": "kunikida (suzumiya haruhi)",
            "阿万音由季（命运石之门）": "amane yuki",
            "天王寺绹（命运石之门）": "tennouji nae",
            "天王寺裕吾（命运石之门）": "tennouji yuugo",
            "椎名篝（命运石之门）": "shiina kagari",
            "巴特（攻壳机动队）": "batou (gits)",
            "户草（攻壳机动队）": "togusa (gits)",
            "荒卷大辅（攻壳机动队）": "aramaki daisuke",
            "石川（攻壳机动队）": "ishikawa (gits)",
            "斋藤（攻壳机动队）": "saitou (gits)",
            "波玛（攻壳机动队）": "boma (gits)",
            "塔奇克马（攻壳机动队）": "tachikoma",
            "富奇科马（攻壳机动队）": "fuchikoma",
            "地场卫（美少女战士）": "chiba mamoru",
            "天王遥（美少女战士）": "ten'ou haruka",
            "海王满（美少女战士）": "kaiou michiru",
            "冥王雪奈（美少女战士）": "meiou setsuna",
            "星野光（美少女战士）": "seiya kou",
            "大气光（美少女战士）": "taiki kou",
            "夜天光（美少女战士）": "yaten kou",
            "早乙女乱马（乱马½）": "saotome ranma",
            "天道靡（乱马½）": "tendou nabiki",
            "天道霞（乱马½）": "tendou kasumi",
            "天道早云（乱马½）": "tendou souun",
            "早乙女玄马（乱马½）": "saotome genma",
            "沐丝（乱马½）": "mousse (ranma 1/2)",
            "裤袜太郎（乱马½）": "pantyhose tarou",
            "九能带刀（乱马½）": "kunou tatewaki",
            "九能小太刀（乱马½）": "kunou kodachi",
            "五寸钉光（乱马½）": "gosunkugi hikaru",
            "阿迪涅（天元突破）": "adiane",
            "达莉·阿代（天元突破）": "darry adai",
            "基米·阿代（天元突破）": "gimmy adai",
            "奇坦·巴奇卡（天元突破）": "kittan bachika",
            "吉永·巴奇卡（天元突破）": "kiyoh bachika",
            "利珑·利特纳（天元突破）": "leeron littner",
            "罗杰侬（天元突破）": "lordgenome",
            "维拉尔（天元突破）": "viral (ttgl)",
            "黎星刻（反叛的鲁路修）": "li xingke",
            "利瓦尔·卡尔德蒙德（反叛的鲁路修）": "rivalz cardemonde",
            "查尔斯·Di·布里塔尼亚（反叛的鲁路修）": "charles zi britannia",
            "修奈泽尔·El·布里塔尼亚（反叛的鲁路修）": "schneizel el britannia",
            "藤堂镜志朗（反叛的鲁路修）": "toudou kyoushirou",
            "篠崎咲世子（反叛的鲁路修）": "shinozaki sayoko",
            "阿列克斯·路易·阿姆斯特朗（钢之炼金术士）": "alex louis armstrong",
            "格拉托尼（钢之炼金术士）": "gluttony (fma)",
            "格利德（钢之炼金术士）": "greed (fma)",
            "马斯·休斯（钢之炼金术士）": "maes hughes",
            "普莱德（钢之炼金术士）": "pride (fma)",
            "斯卡（钢之炼金术士）": "scar (fma)",
            "斯洛斯（钢之炼金术士）": "sloth (fma)",
            "泉·卡迪斯（钢之炼金术士）": "izumi curtis",
            "佐尔夫·J·金布利（钢之炼金术士）": "solf j. kimblee",
            "柊美纪（幸运星）": "hiiragi miki",
            "泉彼方（幸运星）": "izumi kanata",
            "泉总次郎（幸运星）": "izumi soujirou",
            "黑井奈那子（幸运星）": "kuroi nanako",
            "峰岸绫乃（幸运星）": "minegishi ayano",
            "成实唯（幸运星）": "narumi yui",
            "帕特莉西亚·马汀（幸运星）": "patricia martin",
            "白石稔（幸运星）": "shiraishi minoru",
            "田村日和（幸运星）": "tamura hiyori",
            "犬夜叉（犬夜叉）": "inuyasha (character)",
            "弥勒（犬夜叉）": "miroku (inuyasha)",
            "七宝（犬夜叉）": "shippou (inuyasha)",
            "桔梗（犬夜叉）": "kikyou (inuyasha)",
            "铃（犬夜叉）": "rin (inuyasha)",
            "邪见（犬夜叉）": "jaken",
            "神乐（犬夜叉）": "kagura (inuyasha)",
            "琥珀（犬夜叉）": "kohaku (inuyasha)",
            "钢牙（犬夜叉）": "kouga (inuyasha)",
            "云母（犬夜叉）": "kirara (inuyasha)",
            "诸叶（犬夜叉）": "moroha",
            "奈落（犬夜叉）": "naraku (inuyasha)",
            "诸星当（福星小子）": "moroboshi ataru",
            "三宅忍（福星小子）": "miyake shinobu",
            "面堂终太郎（福星小子）": "mendou shuutarou",
            "藤波龙之介（福星小子）": "fujinami ryuunosuke",
            "弁天（福星小子）": "benten (urusei yatsura)",
            "小天（福星小子）": "ten (urusei yatsura)",
            "兰（福星小子）": "ran (urusei yatsura)",
            "阿雪（福星小子）": "oyuki (urusei yatsura)",
            "错乱坊（福星小子）": "cherry (urusei yatsura)",
            "樱花（福星小子）": "sakura (urusei yatsura)",
            "克拉玛（福星小子）": "kurama (urusei yatsura)",
            "眼镜（福星小子）": "megane (urusei yatsura)",
            "波卷（福星小子）": "perm (urusei yatsura)",
            "艾基尔（刀剑神域）": "agil",
            "克莱因（刀剑神域）": "klein (sao)",
            "阿尔戈（刀剑神域）": "argo the rat",
            "须乡伸之（刀剑神域）": "sugou nobuyuki",
            "茅场晶彦（刀剑神域）": "kayaba akihiko",
            "尤吉欧（刀剑神域）": "eugeo",
            "幸（刀剑神域）": "sachi (sao)",
            "西莉卡（刀剑神域）": "silica",
            "吉尔伯特·布干维利亚（紫罗兰永恒花园）": "gilbert bougainvillea",
            "克劳迪娅·霍金斯（紫罗兰永恒花园）": "claudia hodgins",
            "迪特弗里特·布干维利亚（紫罗兰永恒花园）": "dietfried bougainvillea",
            "爱丽丝·卡纳利（紫罗兰永恒花园）": "iris cannary",
            "卡塔莉娜·博德莱尔（紫罗兰永恒花园）": "cattleya baudelaire",
            "露库莉娅·马尔博罗（紫罗兰永恒花园）": "luculia marlborough",
            "艾米·巴特莱特（紫罗兰永恒花园）": "amy bartlett",
            "埃丽卡·布朗（紫罗兰永恒花园）": "erica brown",
            "班尼迪克特·布卢（紫罗兰永恒花园）": "benedict blue",
            "安妮·马格诺利亚（紫罗兰永恒花园）": "ann magnolia",
            "店长（孤独摇滚）": "pa-san",
            "后藤美智代（孤独摇滚）": "gotoh michiyo",
            "乙女樱（莉可丽丝）": "otome sakura",
            "普罗斯佩拉·墨丘利（机动战士高达：水星的魔女）": "prospera mercury",
            "妮卡·七浦（机动战士高达：水星的魔女）": "nika nanaura",
            "黑川茜（我推的孩子）": "kurokawa akane",
            "赞泽（葬送的芙莉莲）": "sense (sousou no frieren)",
            "灰姑娘（胜利女神：NIKKE）": "cinderella (nikke)",
            "贝伊（胜利女神：NIKKE）": "bay (nikke)",
            "艾德（胜利女神：NIKKE）": "ade (nikke)",
            "诺亚尔（胜利女神：NIKKE）": "noir (nikke)",
            "布兰儿（胜利女神：NIKKE）": "blanc (nikke)",
            "爱莲（胜利女神：NIKKE）": "elegg (nikke)",
            "卡罗琳（尘白禁区）": "caroline (snowbreak)",
            "知更鸟（崩坏：星穹铁道）": "robin (honkai: star rail)",
            "灰原哀（名侦探柯南）": "haibara ai",
            "玉叶妃（药屋少女的呢喃）": "gyokuyou (kusuriya no hitorigoto)",
            "若月妮可（WITCH WATCH）": "wakatsuki nico",
            "小舟潮（夏日重现）": "kofune ushio",
            "胡蝶忍（鬼灭之刃）": "kochou shinobu",
            "约尔·福杰（间谍过家家）": "yor briar",
            "玛露希尔（迷宫饭）": "marcille donato",
            "尤贝尔（葬送的芙莉莲）": "ubel (sousou no frieren)",
            "山田杏奈（我心里危险的东西）": "yamada anna",
        }
        for chinese_name, tag in expected.items():
            with self.subTest(chinese_name=chinese_name):
                prompt, info = self.node.select_character(
                    chinese_name, 0, 1.0, False, "masterpiece"
                )
                self.assertIn(tag, prompt.replace("\\", ""))
                self.assertIn(chinese_name, info)

    def test_random_selection_is_seed_deterministic(self) -> None:
        first = self.node.select_character("random", 77, 1.0, False, "")
        second = self.node.select_character("random", 77, 1.0, False, "")
        self.assertEqual(first, second)
        self.assertNotIn("Character: random", first[1])

    def test_weight_and_prompt_order(self) -> None:
        prompt, _ = self.node.select_character(
            "黍（明日方舟）", 0, 1.25, True, "solo"
        )
        self.assertTrue(prompt.startswith("solo, "))
        self.assertIn(":1.25)", prompt)


if __name__ == "__main__":
    unittest.main()
