"""Generate pinyin-initial search data for the character selector ComfyUI extension.

Reads the roster CSV and writes web/extensions/pinyin_data.js as
`globalThis.__CHARACTER_PINYIN__ = { "<cn name>": "<initials>", ... }`.

Initials: first letter of each pinyin syllable of the Chinese display name,
lowercased (e.g. "凯露" -> "kl", "爱丽丝·卡塔雷特" -> "alsktlt").
Only names containing CJK chars get an entry; English tag options are already
searchable directly. Non-CJK tokens (digits/latin/katakana) are skipped.
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

from pypinyin import Style, pinyin

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "data" / "wai_characters.csv"
OUT = ROOT / "web" / "pinyin_data.js"

CJK = re.compile(r"[\u3400-\u9fff\uf900-\ufaff]")


def initials_of(name: str) -> str:
    syl = pinyin(name, style=Style.FIRST_LETTER, errors=lambda _: "")
    out: list[str] = []
    for s in syl:
        if isinstance(s, list):
            s = "".join(s)
        if s:
            out.append(s.lower())
    return "".join(out)


def main() -> None:
    with CSV.open(encoding="utf-8", newline="") as f:
        names = [row[0] for row in csv.reader(f)]
    index: dict[str, str] = {}
    for n in names:
        if CJK.search(n):
            init = initials_of(n)
            if init:
                index[n] = init
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Auto-generated by tools/generate_pinyin_data.py - do not edit.\n"
        "globalThis.__CHARACTER_PINYIN__ = "
        + json.dumps(index, ensure_ascii=False, sort_keys=True)
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} entries={len(index)} size={OUT.stat().st_size}")


if __name__ == "__main__":
    main()
