"""Generate pinyin-initial search data for the character selector ComfyUI extension.

Reads the roster CSV and writes web/extensions/pinyin_data.js as
`globalThis.__CHARACTER_PINYIN__ = { "<cn name>": "<initials>", ... }`.

Initials: first letter of each pinyin syllable of the Chinese display name,
lowercased (e.g. "凯露" -> "kl", "爱丽丝·卡塔雷特" -> "alsktlt").
Only names containing CJK chars get an entry; English tag options are already
searchable directly. Non-CJK tokens (digits/latin/katakana) are skipped.
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

from pypinyin import Style, pinyin

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "data" / "wai_characters.csv"
OUT = ROOT / "web" / "pinyin_data.js"

CJK = re.compile(r"[\u3400-\u9fff\uf900-\ufaff]")


def _syllables(name: str) -> list[str]:
    """Pinyin syllables (or empty) per char, non-CJK tokens dropped."""
    out: list[str] = []
    for syl in pinyin(name, style=Style.NORMAL, errors=lambda _: ""):
        if isinstance(syl, list):
            syl = "".join(syl)
        if syl:
            out.append(syl.lower())
    return out


def initials_of(name: str) -> str:
    return "".join(s[0] for s in _syllables(name) if s)


def full_pinyin_of(name: str) -> str:
    return "".join(_syllables(name))


def main() -> None:
    with CSV.open(encoding="utf-8", newline="") as f:
        names = [row[0] for row in csv.reader(f)]
    index: dict[str, dict[str, str]] = {}
    for n in names:
        if CJK.search(n):
            syl = _syllables(n)
            if syl:
                index[n] = {"i": "".join(s[0] for s in syl), "p": "".join(syl)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Auto-generated by tools/generate_pinyin_data.py - do not edit.\n"
        "globalThis.__CHARACTER_PINYIN__ = "
        + json.dumps(index, ensure_ascii=False, sort_keys=True)
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} entries={len(index)} size={OUT.stat().st_size}")


if __name__ == "__main__":
    main()
